### ISSUE TITLE
Use Algolia DocSearch

### ISSUE THREAD

**Issue by zkan** [zkan/data-engineering-book#50]
We've already applied to the DocSearch program. Now we're waiting for their reply. Many thanks to @kahnwong. Once they reply with a good news, we can enable this cool feature. 😊

See [Using Algolia DocSearch](https://docusaurus.io/docs/search#using-algolia-docsearch) for more detail.

**Comment by kahnwong** [comment]
![image](https://user-images.githubusercontent.com/22489525/198815909-e6e14e83-7d4d-404a-819c-a817e8bb17a4.png)

update: we now can use algolia as search backend. I'll work on the pr some time next month 🚀
