### ISSUE TITLE
เพิ่มหัวข้อ Apache Airflow

### ISSUE THREAD

**Issue by firstnapat** [zkan/data-engineering-book#56]
ผมอยากเพิ่มหัวข้ออธิบายเกี่ยว ariflow แล้วก็วิธีใช้เบื้องต้น ควรสร้างหัวข้อใหม่หรือเอาไปใส่ตรงไหนดีครับ

**Comment by zkan** [comment]
คิดว่าตอนนี้น่าจะใส่เข้าไปตรง https://www.thedataengineeringbook.online/docs/tools#airflow ได้ก่อนนะครับ ในอนาคตอาจจะแยกเป็นหัวข้อใหม่ เพราะคิดว่าเครื่องมือแต่ละตัวก็อาจจะมี section ของตัวมันเอง เอาไว้สำหรับการใช้งานเบื้องต้น ให้คนเริ่มลองเล่นได้แบบง่าย ๆ

@kahnwong พอมีไอเดียเพิ่มเติมไหมเอ่ย

**Comment by kahnwong** [comment]
ทำเป็น sub section ได้

![image](https://user-images.githubusercontent.com/22489525/197113917-a5f042ae-40be-43fb-ba0d-3380e42ecb38.png)
https://github.com/kahnwong/docs/blob/4358b780ba84316bd9ec3501bc0e53e8052b5f74/sidebars.js#L113-L121

**Comment by zkan** [comment]
อ่าา ขอบคุณครับ

@firstnapat ลองทำตามด้านบนเลยครับผม ^

**Comment by firstnapat** [comment]
โอเคครับ งั้นเบื้องต้นผมอาจจะลองใส่เป็น sub section ของ Tools นะครับพี่กานต์

**Comment by zkan** [comment]
ครับผม ตามนั้น
